### PR TITLE
gh-927: Provided mechanism for users to override seed types when using the UI

### LINKED ISSUE #927: UI fails to run OperationChains which have an inputType of ElementId[]
Currently, it is not possible to run an OperationChain using the UI if it starts with an operation which has an input type of `ElementId[]`.

For example:

```json
{
  "operations": [
    { 
      "class": "uk.gov.gchq.gaffer.operation.impl.output.ToVertices",
      "edgeVertices": DESTINATION,
      "input": "testing"
    },
    { 
      "class": "uk.gov.gchq.gaffer.operation.impl.output.ToSet"
    }
  ]
}
```

When created in the UI using the graphical OperationChain builder, gives the error message:

`Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'class' that is to contain type id (for class java.lang.Object) at......`

This is happening because the inputTypeName is determined to be `ElementId[]`

https://github.com/gchq/gaffer-tools/blob/1d4074367f616d0d6ed32244eb5da9b67c5dcb4a/ui/src/main/webapp/app/query/operation-chain-component.js#L288

and this is not a case which is handled by the conditional block responsible for formatting the operation chain before it is sent to the underlying Gaffer REST API.

https://github.com/gchq/gaffer-tools/blob/1d4074367f616d0d6ed32244eb5da9b67c5dcb4a/ui/src/main/webapp/app/query/operation-chain-component.js#L307

I think the behaviour of the `createOpInput` function could be updated to support a wider range of input types, though it's tricky with abstract types like `ElementId` which can't be deserialised without accompanying type information. It might be that we have to assume `ElementId`s are `EntityId`s unless `EdgeId` is stated explicitly, or require explicit types all of them time?

### PR DESCRIPTION
**Pull request by t511203**
* Added some new sub-components to the `<seed-builder>` component to allow users to override the seed type that is inferred by the UI when submitting operations to Gaffer.
* If the override behaviour is selected, a new field value (`overriddenSeedType`) is propagated through to the `OperationChainController`, where it is used to change the seed formatting.
* Added new tests and updated old tests.

Notes:

* Currently this approach doesn't support supplying mixed seed types in a single operation (e.g. being able to submit a `GetElements` operation through the UI which contains input with correctly formatted `EdgeSeeds` and `EntitySeeds`). All input seeds must be overridden to the same type.
* When submitting an operation which contains multiple inputs (`input` and `inputB`), if the input seed type is overridden then this will apply to both `input` and `inputB`.
* `EdgeSeeds` are still unsupported when using the UI.

# Related Issue

- Resolve #927

### CODE REVIEW

**Comment by t511203** [comment]
Placed into draft while I rename some of the fields - I think some of the current names are a bit confusing as they're too similar to one another.

File: ui/src/main/webapp/app/query/input-manager/seed-builder/seed-builder-component.js [hunk 1]
```diff
@@ -48,14 +48,19 @@ function seedBuilder() {
 function SeedBuilderController(schema, csv, types, error, events, common, $routeParams, $location) {
     var vm = this;
     vm.seedVertices = '';
+    vm.forceSeedType = false
+    vm.seedType = ''
+    vm.seedTypes = ('Entity Object').split(' ').map(function (seedType) {
```
Comment (t92549) [inline ui/src/main/webapp/app/query/input-manager/seed-builder/seed-builder-component.js:53]: Is there a reason this is so funky?

**Review by t92549 — COMMENTED** [review]
Overall looks good, how do we feel about not being able to use `EdgeSeeds`? Could this be added too or is there just no need for it?

File: ui/src/main/webapp/app/query/input-manager/seed-builder/seed-builder-component.js (hunk 1 above)
Comment (t511203) [reply ui/src/main/webapp/app/query/input-manager/seed-builder/seed-builder-component.js:53]: This is "shorthand" for:

```javascript
vm.seedTypes = [
    { value: 'Entity' },
    { value: 'Object' },
]
```

But written as a function in case I needed to extend/adapt this object creation. It's probably fine to replace it with the straightforward array declaration instead if that's preferred?

**Comment by t511203** [comment]
> Overall looks good, how do we feel about not being able to use `EdgeSeeds`? Could this be added too or is there just no need for it?

It's a significant amount of work to implement `EdgeSeed`s into the UI, so this would need to be carried out under another ticket (and triaged/prioritised appropriately).

File: ui/src/main/webapp/app/query/input-manager/seed-builder/seed-builder-component.js (hunk 1 above)
Comment (t92549) [reply ui/src/main/webapp/app/query/input-manager/seed-builder/seed-builder-component.js:53]: I think the part that looked odd to me was splitting a string with spaces instead of using a list, but honestly both are fine and like you said extensible.

**Review by t92549 — APPROVED** [review]
